apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: hailo-device-plugin
  namespace: kube-system
  labels:
    app: hailo-device-plugin
spec:
  selector:
    matchLabels:
      app: hailo-device-plugin
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: hailo-device-plugin
    spec:
      hostNetwork: true
      nodeSelector:
        # Add node selector if needed to target specific nodes with Hailo devices
        # kubernetes.io/hostname: <node-name>
      containers:
      - name: hailo-device-plugin
        image: ghcr.io/snu-rtos/hailo-device-plugin:latest
        imagePullPolicy: Always
        securityContext:
          privileged: true
          capabilities:
            add:
            - SYS_ADMIN
        volumeMounts:
        - name: device-plugin
          mountPath: /var/lib/kubelet/device-plugins
        - name: dev
          mountPath: /dev
        - name: cdi
          mountPath: /etc/cdi
        - name: sys
          mountPath: /sys
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
      volumes:
      - name: device-plugin
        hostPath:
          path: /var/lib/kubelet/device-plugins
          type: Directory
      - name: dev
        hostPath:
          path: /dev
          type: Directory
      - name: cdi
        hostPath:
          path: /etc/cdi
          type: DirectoryOrCreate
      - name: sys
        hostPath:
          path: /sys
          type: Directory
      tolerations:
      - key: node-role.kubernetes.io/master
        operator: Exists
        effect: NoSchedule
      - key: node-role.kubernetes.io/control-plane
        operator: Exists
        effect: NoSchedule
